**Python সহ NumPy & pandas**

---

### ১. সূচনা ও উদ্দেশ্য

* আপনি কেন NumPy ও pandas শিখবেন — EE রিসার্চ/প্র্যাকটিসে কেন প্রয়োজন।

  * ইলেকট্রিক্যাল ইঞ্জিনিয়ারিং‑র ক্ষেত্রে যেমন সিগন্যাল ডাটা, ম্যাট্রিক্স অপারেশন, সিমুলেশন ফলাফল, পরীক্ষার ফলাফল (measurement data) ‑‑ এগুলো অনেক বড় বা জটিল হতে পারে।
  * Python + NumPy + pandas দিয়ে সেই ডাটা দ্রুত ও কার্যকরভাবে হ্যান্ডেল করা যায়। যেমন‑ ম্যাট্রিক্স অপারেশন, সার্বিক পরিসংখ্যান বিশ্লেষণ, সময় বা ফ্রিকোয়েন্সি সিরিজ ইত্যাদি।
* এই লেকচারে যা শেখা হবে:

  1. NumPy‑এর প্রধান array কাঠামো, ভেক্টর, ম্যাট্রিক্স অপারেশন।
  2. pandas‑এর Series ও DataFrame — ট্যাবুলার ডাটা ম্যানিপুলেশন।
  3. EE‑র প্রেক্ষাপটে প্রয়োগ‑উদাহরণসহ (সিগন্যাল, সেন্সর ডাটা, পরীক্ষা ফলাফল)।
  4. চর্চা ও বাস্তব সমস্যায় প্রয়োগের জন্য কিছু ছোট পরীক্ষা/কোড স্নিপেট।
* প্রি‑রিকুইজিট: Python ও সাধারণ ডাটাস্ট্রাকচারগুলোর (list, tuple, dict) ধারণা ইতোমধ্যে দেয়া হয়েছে। তাই আমরা সেখান থেকে এক ধাপ এগিয়ে যাব।

---





### ২. NumPy: দ্রুত সংখ্যা‑গণনা ও অ্যারে অপারেশন

#### ২.১ NumPy কি & কেন

* NumPy = Numerical Python: পাইথনে সংখ্যাগত (numerical) গণনা ও বড় অ্যারে‑ম্যাট্রিক্স কার্যকরভাবে করার জন্য লাইব্রেরি। ([NumPy][1])
* এক কথায় বললে: সাধারণ পাইথন লুপে কাজ করলে ধীর হয়; NumPy‑এর “ভেক্টরাইজড” (vectorized) অপারেশন অনেক দ্রুত। ([Dataquest][2])
* EE‑র প্রসঙ্গঃ ইলেকট্রিক্যাল সিগন্যাল, সময়‑সিরিজ, সেন্সর রিডিং, ম্যাট্রিক্স ফরম্যাটে সিস্টেম নির্ণয় (system analysis) এসব ক্ষেত্রে ম্যাট্রিক্স/ভেক্টর অপারেশন প্রচুর হয় — NumPy‑এ খুব সুবিধা হয়।

#### ২.২ NumPy ইনস্টল ও ইম্পোর্ট



In [1]:
import numpy as np
print(np.__version__)   # সংস্করণ জানার জন্য

1.24.3


In [2]:
# কয়েকটা সিম্পল অ্যারে তৈরি করি
a = np.array([1, 2, 3, 4])
print("a =", a)

a = [1 2 3 4]


আউটপুট হবে: `a = [1 2 3 4]`

#### ২.৩ অ্যারে (array) — ১D, ২D, ndim, shape


In [3]:
v = np.array([10,20,30])          # ১‑D ভেক্টর
M = np.array([[1,2,3],[4,5,6]])   # ২×৩ ম্যাট্রিক্স
print(v.ndim, v.shape)
print(M.ndim, M.shape)

1 (3,)
2 (2, 3)


* `ndim` হলো মাত্রা (dimension) — এখানে `v.ndim = 1`, `M.ndim = 2`
* `shape` হলো আকার (rows×columns) — `v.shape = (3,)`, `M.shape = (2,3)`
  এই ধারণাগুলো EE‑র জন্য গুরুত্বপূর্ণ। যেমন: একটি সেন্সর রিডিং হতে পারে (সময় ধরে) ভেক্টর, একটি ট্রান্সফার ম্যাট্রিক্স হতে পারে ২D অ্যারে।

#### ২.৪ মৌলিক অপারেশন: অ্যারে সঙ্গে অ্যারে, স্কেলার সঙ্গে অ্যারে



In [4]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a + b)         # [11 22 33]
print(a * 2)         # [2 4 6]
print(a ** 2)        # [1 4 9]

[11 22 33]
[2 4 6]
[1 4 9]



**“সারি–সারি” অপারেশন মানে প্রতিটি উপাদান আলাদা আলাদা ভাবে হয়।**

যদি আপনার সময়‑সিরিজ হয় `voltage = np.array([...])`, তাহলে আপনি `power = voltage ** 2 / resistance` এই রুপরেখায় দ্রুত গণনা করতে পারবেন।

#### ২.৫ রিসাইজ, রিফর্ম (reshape) এবং ট্রান্সপোজ (transpose)



In [5]:
M = np.array([[1,2,3],[4,5,6]])
M2 = M.reshape((3,2))
print(M2)
print(M.T)   # ট্রান্সপোজ

[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


**অনেক সময় আপনার ম্যাট্রিক্সের রূপ পরিবর্তন করতে হয় — যেমন সিগন্যালকে (time × channel) ফরম্যাটে রূপান্তর করা। বাংলায় বললে: “৩×২ এ রিফর্ম করা হলো তিন সময় স্টেপ্টে দুই চ্যানেলের রিডিং” ইত্যাদি।**

#### ২.৬ ইনডেক্সিং, স্লাইসিং, ফিল্টারিং

In [6]:
a = np.array([10,20,30,40,50])
print(a[2])         # তৃতীয় উপাদান = 30
print(a[1:4])       # ২য়‑৪র্থ উপাদান = [20 30 40]
print(a[a > 25])    # অবস্থা প্রয়োগ: [30 40 50]

30
[20 30 40]
[30 40 50]


**“যে উপাদানগুলো ২৫‑এর বড়” এর ফল হল [30,40,50]।**

EE‑র ব্যবহার: সেন্সর রিডিং যদি `readings = np.array(...)` হয়, তাহলে আপনি সহজে “যে রিডিংগুলো নির্দিষ্ট থ্রেশহোল্ডের বেশি” সিলেক্ট করে ফেলতে পারবেন।

#### ২.৭ লিনিয়ার অ্যালজেব্রা, ম্যাথম্যাটিকাল ইউটিলিটিস

NumPy‑তে অনেক ফাংশন আছে: `np.sum`, `np.mean`, `np.dot`, `np.linalg.inv`, ইত্যাদি।
ইঞ্জিনিয়ারিং ক্ষেত্রে যেমন সিস্টেম ম্যাট্রিক্সের ইনভার্স বা Eigenvalue নিরূপণ, এসবই এখানে আসে। শুধু সাধারণ ধারণা: একবার অ্যারে বা ম্যাট্রিক্সে দক্ষ হয়ে গেলে, EE‑র রিসার্চ‑এ দ্রুত প্রয়োগ সহজ হয়।

#### ২.৮ উদাহরণ (বাংলায়)



In [7]:
# ধরুন পরীক্ষা রিডিং আছে প্রতি সেকেন্ডে ভোল্টেজ:
voltage = np.array([0.1, 0.2, 0.15, 0.25, 0.3])
resistance = 5.0  # ওহম
current = voltage / resistance
power = voltage * current  # P = V * I
print("Current:", current)
print("Power:", power)

Current: [0.02 0.04 0.03 0.05 0.06]
Power: [0.002  0.008  0.0045 0.0125 0.018 ]


**প্রতিটি সেকেন্ডে ভোল্টেজ রিডিং থেকে কারেন্ট ও শক্তি নিরূপণ করা হলো — NumPy দিয়ে এক লাইনে অনেক উপাদান নিয়ে কাজ করা যেতে পারে।**

### ৩. pandas: ট্যাবুলার ডাটা ম্যানিপুলেশন

#### ৩.১ pandas কি & কেন

* pandas হলো পাইথনের একটি ওপেন‑সোর্স লাইব্রেরি যা ডাটা ম্যানিপুলেশন ও বিশ্লেষণ সহজ করে তোলে। [3]
* এর মূল ডাটা স্ট্রাকচার: `Series` (১D) এবং `DataFrame` (২D টেবিল)। [4]
* EE‑তে কেন গুরুত্বপূর্ণ: আপনি যদি পরীক্ষার ফলাফল (যেমন সময়‑সিগন্যাল, ভোল্টেজ/কারেন্ট রিডিং, সেন্সর লোগ ডাটা) এক্সেল/CSV ফাইলে রাখেন, তাহলে pandas দিয়ে তা সহজে লোড, ক্লিন, বিশ্লেষণ করা যাবে।

#### ৩.২ ইনস্টল ও ইম্পোর্ট


In [8]:
pip install pandas numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd
print(pd.__version__)

In [ ]:
# CSV ফাইল থেকে ডাটা লোড
df = pd.read_csv("sensor_readings.csv")


#### ৩.৩ Series ও DataFrame: পরিচিতি

In [ ]:
s = pd.Series([100, 200, 300], index=['a','b','c'])
print(s)
df = pd.DataFrame({
    'time_s': [0,1,2],
    'voltage': [0.1,0.2,0.15],
    'current': [0.02,0.04,0.03]
})
print(df)

**Series হলো এক কলামের ডাটা (লেবেলসহ), DataFrame হলো একাধিক কলামসহ একটি টেবিল রূপের ডাটা।**


#### ৩.৪ DataFrame‑এর মৌলিক অপারেশন

* `df.head()`, `df.tail()` → প্রথম/শেষ কিছু রেকর্ড দেখার জন্য
* `df.info()`, `df.describe()` → ডাটার সারাংশ ও তথ্য
* কলাম নির্বাচন: `df['voltage']`, `df[['voltage','current']]`
* সারি নির্বাচন: `df.iloc[0]`, `df.loc[ df['time_s']==1 ]`
* নতুন কলাম সৃষ্টি: `df['power'] = df['voltage'] * df['current']`
  বাংলায়: “নতুন কলাম সৃষ্টি করা হলো শক্তি (power) যা ভোল্টেজ ও কারেন্টকে গুণ করে পাওয়া হয়েছে”।

#### ৩.৫ মিসিং বা অনুপস্থিত ডাটা হ্যান্ডেলিং

* `df.dropna()` → মিসিং ভ্যালু সহ সারি বা কলাম বাদ দেওয়া
* `df.fillna(value)` → অনুপস্থিত ডাটায় প্রতিস্থাপন
  এগুলো pandas‑এর অত্যাবশ্যক ফিচার। ([DataCamp][5])
  বাংলায়: গবেষণার সময় কখনও সেন্সর রিডিং মিস হতে পারে — সেক্ষেত্রে এই মেথডগুলো কাজে লাগে।

#### ৩.৬ গ্রুপিং, সংক্ষেপণ ও রিশেপিং

* `df.groupby('sensor_id').mean()` → সেন্সর আইডি অনুযায়ী গড় নিরূপণ
* `df.pivot_table(...)` → টেবিল রূপান্তর
* `df.merge(...)`, `df.concat(...)` → একাধিক DataFrame যুক্ত করা
  এসব pandas‑এর শক্তিশালী ফিচার। ([Medium][6])
  বাংলায়: “যদি একাধিক সেন্সরের রিডিং থাকে এবং আপনাকে সেন্সর অনুযায়ী গড় বা সর্বোচ্চ মান বের করতে হয়, তাহলে গ্রুপবাই ব্যবহার করবেন”।

#### ৩.৭ ইলেকট্রিক্যাল ইঞ্জিনিয়ারিং উদাহরণ (বাংলায়)


In [ ]:
import pandas as pd

# ধরুন একটি CSV আছে: time_s, voltage, current, sensor_id
df = pd.read_csv("experiment1.csv")

# নতুন কলাম: power
df['power'] = df['voltage'] * df['current']

# সেন্সর অনুযায়ী গড় শক্তি নিরূপণ
avg_power_sensor = df.groupby('sensor_id')['power'].mean()

print(avg_power_sensor)

**“প্রতি সেন্সরের জন্য গড় শক্তি নিরূপণ করা হলো”।**


#### ৩.৮ ফাইল I/O (ইনপুট/আউটপুট)

* `pd.read_csv()`, `pd.read_excel()` → লোড করা
* `df.to_csv()`, `df.to_excel()` → ফলাফল সংরক্ষণ করা ([Medium][6])
  বাংলায়: “আপনার বিশ্লেষণ শেষ হলে সেটি CSV হিসেবে সেভ করে রাখতে পারেন”।

---


### ৪. NumPy ও pandas একসঙ্গে — প্রয়োগভিত্তিক

#### ৪.১ সিগন্যাল প্রসেসিং উদাহরণ

* ধরুন সময়সীমা ধরে ভোল্টেজ রেকর্ড আছে: `voltage = np.array(...)`
* আমরা নিরূপণ করব রিয়াল শক্তি, শক্তি ফ্লাকচুয়েশন, এবং সেই রেকর্ডগুলো DataFrame‑এ রাখতে পারি।
* উদাহরণ কোড (বাংলায় মূল বিবরণসহ):



In [ ]:
import numpy as np
import pandas as pd

# সময় (সেকেন্ডে) এবং রিডিং
time_s = np.array([0,1,2,3,4])
voltage = np.array([0.1,0.2,0.18,0.25,0.3])
resistance = 5.0

current = voltage / resistance
power = voltage * current

df = pd.DataFrame({
    'time_s': time_s,
    'voltage': voltage,
    'current': current,
    'power': power
})

print(df)

**এই কোডে প্রথমে NumPy দিয়ে ভেক্টরগুলো তৈরি করা হলো, তারপর pandas‑এ টেবিল রূপে সেটিকে পরিণত করা হলো যেটা পরবর্তী বিশ্লেষণ বা ভিজ্যুয়ালাইজেশনের জন্য খুব সুবিধাজনক।**




#### ৪.২ রিসার্চ প্রশ্ন উদাহরণ

* সেন্সর রিডিং‑এর মধ্যে কোন সময় বেশি শক্তি খরচ হয়েছে?
* বিভিন্ন সেন্সরের রিডিং তুলনায় পার্থক্য আছে কি?
* সময়সাপেক্ষ ভোল্টেজ‑রূপান্তর বিশ্লেষণ করা যায় কি না?

এই প্রশ্নগুলোর উত্তর দিতে আপনি pandas‑এর ফিল্টারিং, গ্রুপবাই, বা রিসেম্পলিং (time series) ব্যবহার করতে পারবেন।

---




### ৫. বাস্তব জীবনের টিপস ও ভাল অভ্যাস

* **ভেক্টরাইজেশন** ব্যবহার করুন: মধ্যস্থ লুপ এড়িয়ে চলুন — বিশেষ করে বড় ডাটাসেটে। ([Dataquest][2])
* ডাটা ক্লিনিং গুরুত্বপূর্ণ: নয়তো ফলাফল বিশ্বাসযোগ্য হবে না। (মিসিং, ডুপ্লিকেট, আউটলাইয়ার)
* ডকুমেন্টেশন পড়ুন: NumPy ও pandas‑এর অফিসিয়াল গাইড খুব ভালো। ([Pandas][7])
* EE‑র ক্ষেত্রে ডাটা হয়তো সিগন্যাল রিডিং, পরীক্ষার ফলাফল, সময়‑সিরিজ আকারে হবে — সেই অনুযায়ী DataFrame ডিজাইন করুন (সময় কলাম, সেন্সর আইডি, মাপকাঠি ইত্যাদি)।
* কোড রিইউসেবল রাখুন: ফাংশন হিসেবে লেখুন — যেমন `compute_power(voltage, resistance)` ইত্যাদি।
* বিশ্লেষণ ফলাফল সেভ করুন: CSV/Excel আকারে, ভবিষ্যতে রেফারেন্স বা রিসার্চ পেপার‑এ ব্যবহারযোগ্য হবে।

---



### ৬. প্রাকটিস সেশন

#### ৬.১ ছোট চ্যালেঞ্জ

1. একটি NumPy অ্যারে তৈরি করুন যার মধ্যে ১০০টি এলোমেলো ভোল্টেজ রিডিং আছে। তারপর তার থেকে কারেন্ট নিরূপণ করুন ধরেই রেসিস্ট্যান্স = 10Ω।
2. একটি pandas DataFrame তৈরি করুন যার কলাম হচ্ছে `time_s` (0 – 99 সেকেন্ড), `voltage`, `current`। তারপর একটি নতুন কলাম যুক্ত করুন `power = voltage * current` এবং তার পর গড় শক্তি নিরূপণ করুন।
3. যদি সময়সাপেক্ষ ডাটা হয়, তাহলে দেখুন কখন প্রেক্ষাপটে (time > 50 সেকেন্ড) শক্তি সবচেয়ে বেশি ছিল।



#### ৬.২ বড় চ্যালেঞ্জ

EE‑র রিসার্চ প্রেক্ষাপটে ধরুন: সেন্সর একাধিক দিনের রিডিং করেছে, একটি CSV ফাইলে আছে — `sensor_id`, `time_s`, `voltage`, `current`।
আপনাকে করা:

* লোড করুন DataFrame‑এ,
* প্রতিটি সেন্সরের জন্য গড় শক্তি নিরূপণ করুন,
* একাধিক সেন্সরের শক্তি তুলনা করুন,
* সময়সাপেক্ষে প্লট করুন (যদি চান, matplotlib দিয়ে)।

---

### ৭. সংক্ষেপে (Recap)

* NumPy = দ্রুত অ্যারে‑ভিত্তিক গণনা, ম্যাট্রিক্স অপারেশন।
* pandas = ট্যাবুলার ডাটা (Series/DataFrame) হ্যান্ডেল করা সহজ।
* EE‑র রিসার্চ ও বাস্তব প্রয়োগে এই দুই লাইব্রেরি খুব কার্যকর।
* ভালো অভ্যাস (ভেক্টরাইজেশন, ডাটা ক্লিনিং, কোড রিইউসেবেল) অনুসরণ করুন।

---

### ৮. পরবর্তী ধাপ

* তেমন মানের একটি **রিয়েল ডাটা সেট** নিয়ে কাজ করুন (EE‑সিমুলেশন রেজাল্ট, সেন্সর লোগ বা পরীক্ষার ফল) এবং NumPy/pandas দিয়ে বিশ্লেষণ করুন।
* সংশ্লিষ্ট ভিজ্যুয়ালাইজেশন (যেমন প্লট, হিটম্যাপ) শিখতে শুরু করুন — কারণ রিসার্চে শুধু সংখ্যায় নয়, গ্রাফিক্যাল উপস্থাপন গুরুত্বপূর্ণ।
* উচ্চস্তরের বিষয় যেমন সময়‑সিরিজ রিস্যাম্পলিং, পাইভট টেবিল, মাল্টি‑ভ্যারিয়েট বিশ্লেষণ (multiple columns) শেখার প্রস্তুতি নিন।
* EE‑র নির্দিষ্ট প্রয়োজনে (যেমন ফ্রিকোয়েন্সি ডোমেইন, FFT, সিগন্যাল ফিল্টারিং) Python+NumPy+SciPy জুড়ে ফেলুন — কিন্তু এখন সেই step-গুলোর জন্য ভালো ভিত্তি বানানো জরুরি।

---


- The absolute basics for beginners — NumPy v2.4.dev0 Manual https://numpy.org/devdocs//user/absolute_beginners.html?

- Tutorial 1: Introduction to NumPy and pandas for Data Analysis https://www.dataquest.io/tutorial/numpy-and-pandas-for-data-analysis/

- Pandas Tutorial - GeeksforGeeks https://www.geeksforgeeks.org/pandas/pandas-tutorial/

- Pandas Tutorial - GeeksforGeeks https://www.geeksforgeeks.org/pandas-tutorial/

- Python pandas Tutorial: The Ultimate Guide for Beginners - DataCamp https://www.datacamp.com/tutorial/pandas?

- Pandas for Data Engineering! - Medium https://medium.com/%40rganesh0203/pandas-for-data-engineering-a00947eccfdd?

- Community tutorials — pandas 2.3.0 documentation https://pandas.pydata.org/docs/getting_started/tutorials.html